// <auto-generated />
using System;
using FreelanceStudent.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FreelanceStudent.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220515125725_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FreelanceStudent.Entity.Entities.Advert", b =>
                {
                    b.Property<int>("AdvertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 5, 15, 15, 57, 24, 359, DateTimeKind.Local).AddTicks(5061));

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("AdvertId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Adverts");

                    b.HasData(
                        new
                        {
                            AdvertId = 1,
                            CategoryId = 1,
                            CreatedTime = new DateTime(2022, 5, 15, 15, 57, 24, 369, DateTimeKind.Local).AddTicks(2808),
                            Deadline = new DateTime(2022, 5, 20, 15, 57, 24, 369, DateTimeKind.Local).AddTicks(3654),
                            Detail = "Ders için bir proje",
                            IsActivated = true,
                            Price = 100m,
                            Title = "Freelance Student"
                        });
                });

            modelBuilder.Entity("FreelanceStudent.Entity.Entities.Background", b =>
                {
                    b.Property<int>("BackgroundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Github")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BackgroundId");

                    b.ToTable("Backgrounds");

                    b.HasData(
                        new
                        {
                            BackgroundId = 1,
                            Department = "Software Engineer"
                        });
                });

            modelBuilder.Entity("FreelanceStudent.Entity.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Yazılım"
                        });
                });

            modelBuilder.Entity("FreelanceStudent.Entity.Entities.ForeignLanguage", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BackgroundId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.HasIndex("BackgroundId");

                    b.ToTable("ForeignLanguages");
                });

            modelBuilder.Entity("FreelanceStudent.Entity.Entities.JobExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BackgroundId")
                        .HasColumnType("int");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.ToTable("JobExperiences");
                });

            modelBuilder.Entity("FreelanceStudent.Entity.Entities.ProgrammingLanguage", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BackgroundId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.HasIndex("BackgroundId");

                    b.ToTable("ProgrammingLanguages");
                });

            modelBuilder.Entity("FreelanceStudent.Entity.Entities.Advert", b =>
                {
                    b.HasOne("FreelanceStudent.Entity.Entities.Category", "Category")
                        .WithMany("Adverts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FreelanceStudent.Entity.Entities.ForeignLanguage", b =>
                {
                    b.HasOne("FreelanceStudent.Entity.Entities.Background", "Background")
                        .WithMany("ForeignLanguages")
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");
                });

            modelBuilder.Entity("FreelanceStudent.Entity.Entities.JobExperience", b =>
                {
                    b.HasOne("FreelanceStudent.Entity.Entities.Background", "Background")
                        .WithMany("JobExperiences")
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");
                });

            modelBuilder.Entity("FreelanceStudent.Entity.Entities.ProgrammingLanguage", b =>
                {
                    b.HasOne("FreelanceStudent.Entity.Entities.Background", "Background")
                        .WithMany("ProgrammingLanguages")
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");
                });

            modelBuilder.Entity("FreelanceStudent.Entity.Entities.Background", b =>
                {
                    b.Navigation("ForeignLanguages");

                    b.Navigation("JobExperiences");

                    b.Navigation("ProgrammingLanguages");
                });

            modelBuilder.Entity("FreelanceStudent.Entity.Entities.Category", b =>
                {
                    b.Navigation("Adverts");
                });
#pragma warning restore 612, 618
        }
    }
}
